### ISSUE TITLE
Add Feature import file to svn.

### ISSUE THREAD

**Issue by nunompad** [hyung-hwan/codepot#1]
Can you add the feature to import file to the svn repository link you can do on the wiki side.

A import a file will make a new file in the svn a a new commit.

Can you add this feature.

Tks.

**Comment by hyung-hwan** [comment]
Please see d9cd3c48da5e183a27d266bf6dadf9874e7e19ec. it's working but still primitive.

**Comment by nunompad** [comment]
Tks I testes and is working. From my parte this issue is done.

Tks.
